[project]
name = "VDSApp"
description = "Unofficial client for managing Selectel VDS servers. An application based on the Flet library that allows you to work with rented servers directly from your phone. Created for educational purposes."
readme = "README.md"
requires-python = ">=3.12,<3.14"
authors = [
    { name = "Duvakin Andrei", email = "andrei@duvakin.ru" }
]
dependencies = [
    "flet (>=0.86.5,<0.87.0)",
    "dataclass-rest (>=0.5.0,<0.6.0)",
    "aiohttp (>=3.14.0, <4.0.0)",
    "flet-secure-storage (==0.86.5)"
]

[dependency-groups]
dev = [
    "flet-desktop>=0.86.5",
    "flet-web>=0.86.5",
    "flet[test]>=0.86.5",
    "flake8 (>=7.3.0,<8.0.0)",
    "flake8-pyproject (>=1.2.4,<2.0.0)",
    "black (>=26.5.1,<27.0.0)",
    "flake8-bugbear (>=25.11.29,<26.0.0)",
    "flake8-return (>=1.2.0,<2.0.0)",
    "flake8-import-order (>=0.19.2,<0.20.0)",
]

[tool.flet]
org = "com.duvakin"
artifact = "VDSApp"
bundle_id = "com.duvakin.vdsapp"
build_number = 3 # TODO: Изменить версию
version = "0.0.3"
product = "VDSApp"
company = "Andrei Duvakin"
copyright = "Copyright (C) 2026 by Andrei Duvakin"
icon_background = "#1a1a2e"

[tool.flet.splash]
android = true
ios = true
web = true

[tool.flet.boot_screen.flet]
theme_mode = "auto"
bgcolor_light = "#ffffff"
bgcolor_dark = "#000000"
spinner_color_light = "#1a1a2e"
spinner_color_dark = "#72a4c1ff"
spinner_size = 30
text_color_light = "#000000"
text_color_dark = "#ffffff"
prepare_message = "Подготовка приложения к запуску"
startup_message = "Запуск приложения"
fade_out_duration = 450

[tool.flet.android]
min_sdk_version = 24

[tool.flet.app]
path = "."
module = "main"
exclude = [
    ".venv",
    "venv",
    "env",
    ".git",
    ".github",
    ".gitignore",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "build",
    "dist",
    "*.egg-info",
    ".idea",
    ".vscode",
    "*.log",
    "*.db",
    "*.sqlite3",
    "tests",
    "docs",
    "poetry.lock",
    "README.md",
]

[tool.poetry]
package-mode = false

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "constants.py",
]
per-file-ignores = [
    "__init__.py:F401",
]

# flake8-import-order
import-order-style = "google"
application-import-names = ["src.api", "src.core", "src.models", "src.routing", "src.services", "src.state", "src.ui", "src.app", "src.controllers", "main"]

# flake8-bugbear
extend-select = ["B"]

# flake8-return
ignore = ["R504"]

[tool.black]
line-length = 88
target-version = ["py310", "py311", "py312", "py313"]
include = '\.pyi?$'
exclude = '''
/(
    \.venv
  | __pycache__
  | build
  | dist
)/
'''


